version: "3.8"

services:
  geoserver:
    image: kartoza/geoserver:2.23.0
    container_name: geoserver
    restart: unless-stopped
    env_file:
      - .env.cloud
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - ENABLE_JSONP=true
      - MAX_FILTER_RULES=20
      - OPTIMIZE_LINE_WIDTH=false
      - FOOTPRINTS_DATA_DIR=/opt/footprints_dir
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - GEOSERVER_FILEBROWSER_HIDEFS=false
      - STABLE_EXTENSIONS=wps-extension,csw-extension
      - COMMUNITY_EXTENSIONS=
      - CORS_ENABLED=true
      - CORS_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_METHODS=GET,POST,PUT,HEAD,OPTIONS
      - CORS_ALLOWED_HEADERS=*
    ports:
      - "${GEOSERVER_PORT:-8080}:8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - ./sample-data:/sample-data

volumes:
  geoserver_data:
